/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dbbvs' at '12/22/16 5:47 PM' with Gradle 2.14.1
 *
 * @author dbbvs, @date 12/22/16 5:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
